[package]
name = "smart_contract_sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
sha3 = "0.10.8"
syn = {version =  "2.0.104", features = ["full"]}

[lib]
proc-macro = true

[dev-dependencies]
trybuild = "1.0"